CREATE TABLE `item` (
	`ID` INT(11) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL,
	`NAME` VARCHAR(255) NULL DEFAULT NULL,
	`PRICE` DOUBLE NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);


CREATE TABLE `user_order` (
	`USER_ORDER_ID` INT(11) NOT NULL,
	`CITY` VARCHAR(255) NULL DEFAULT NULL,
	`NAME` VARCHAR(255) NULL DEFAULT NULL,
	`ORDER_DATE` DATETIME NULL DEFAULT NULL,
	`STREET` VARCHAR(255) NULL DEFAULT NULL,
	`ZIP` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`USER_ORDER_ID`)
);

CREATE TABLE `ordered_item` (
	`ID` INT(11) NOT NULL,
	`QUANTITY` INT(11) NULL DEFAULT NULL,
	`ITEM_ID` INT(11) NULL DEFAULT NULL,
	`USER_ORDER_ID` INT(11) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
);

